directivo/urls.py
from django.urls import path, re_path

from directivo.views import adm_directivos, adm_sanciones

urlpatterns = [
    # MÓDULO DIRECTIVOS
    re_path(r'^adm_directivos$', adm_directivos.view, name='directivo_adm_directivos'),
    re_path(r'^adm_sanciones$', adm_sanciones.view, name='directivo_adm_sanciones'),
]

directivo/models/models_sanciones.py
#OTROS
from datetime import datetime, timedelta
from unidecode import unidecode

#DJANGO
from django.db import models
from django.contrib.contenttypes.models import ContentType

#CORE
from core.choices.models.sagest import (TIPO_FALTA,ESTADO_DESICION_AUDIENCIA, PUNTO_CONTROL, TIPO_REQUISITO, ESTADO_SANCION_PERSONA,ESTADO_AUDIENCIA,
                                        ESTADO_INCIDENCIA, ACCION_REALIZADA, TIPO_DOCUMENTOS,ESTADO_PRUEBA_DESCARGO,
                                        ESTADO_LEGALIZACION_DOCUMENTO, ETAPA_INCIDENCIA, ROL_FIRMA_DOCUMENTO, ESTADO_APROBACION_ASISTENCIA,
                                        ESTADO_NOTIFICACION_SANCION, ESTADO_FIRMA_ACCION_PERSONAL_SANCION)
#SGA
from sga.funciones import ModeloBase


# Manual de funciones
class ManualFuncion(ModeloBase):
    persona = models.ForeignKey('sga.Persona', on_delete=models.CASCADE, verbose_name='Persona')
    perfilpuesto = models.ForeignKey('sagest.PerfilPuestoTh', on_delete=models.CASCADE, verbose_name='Perfil Puesto')

    def __str__(self):
        return f'{self.persona} | {self.perfilpuesto}'

    class Meta:
        verbose_name = 'Manual de Función'
        verbose_name_plural = 'Manuales de Funciones'
        ordering = ['-id']

class ManualFuncionActividad(ModeloBase):
    manualfuncion = models.ForeignKey(ManualFuncion, on_delete=models.CASCADE, verbose_name='Manual de Función')
    descripcion = models.TextField(default='', verbose_name='Descripción')

    def __str__(self):
        return self.descripcion

    class Meta:
        verbose_name = 'Detalle de Manual de Función'
        verbose_name_plural = 'Detalles de Manuales de Funciones'
        ordering = ['-id']

class RequisitoSancion(ModeloBase):
    nombre = models.CharField(default='', max_length=200, verbose_name='Nombre del requisito de la sanción')
    descripcion = models.TextField(default='', verbose_name='Descripción')
    tiporequisto = models.IntegerField(default=1, choices=TIPO_REQUISITO, verbose_name='Tipo de requisito')

    def __str__(self):
        return self.nombre

    def formatos_permitidos(self):
        if self.tiporequisto == 2:
            return ['.png', '.jpg', '.jpeg']
        return ['.pdf']
    def icono(self):
        if self.tiporequisto == 1:
            return 'bi bi-camera-video'
        elif self.tiporequisto == 2:
            return 'bi bi-image'
        elif self.tiporequisto == 3:
            return 'bi bi-filetype-pdf'
        return 'bi bi-link-45deg'

    def type_input(self):
        if self.tiporequisto in [1, 4]:
            return 'url'
        return 'file'

    def existe_requisitomotivosancion(self):
        return self.requisitomotivosancion_set.filter(status=True).values('id').exists()

    class Meta:
        verbose_name = 'Requisito de sanción'
        verbose_name_plural = 'Requisitos de sanciones'
        ordering = ['-id']

class FaltaDisciplinaria(ModeloBase):
    regimen_laboral = models.ForeignKey('sagest.RegimenLaboral', on_delete=models.CASCADE, verbose_name='Regimen laboral')
    nombre = models.CharField(default='', max_length=200, verbose_name='Nombre de la falta disciplinaria')
    descripcion = models.TextField(default='', verbose_name='Descripción')
    articulo = models.TextField(default='', verbose_name='Articulo')
    motivacionjuridica = models.TextField(default='', verbose_name='Motivacion Juridica')

    def __str__(self):
        return self.nombre

    def motivos(self):
        return self.motivosancion_set.filter(status=True)
    def motivos_principales(self):
        return self.motivosancion_set.filter(status=True, principal=True)
    class Meta:
        verbose_name = 'Falta Disciplinaria'
        verbose_name_plural = 'Faltas Disciplinarias'
        ordering = ['-id']

class MotivoSancion(ModeloBase):
    falta = models.ForeignKey(FaltaDisciplinaria,  blank=True, null=True, verbose_name=u'Falta Disciplinaria', on_delete=models.CASCADE)
    motivoref = models.ForeignKey('self', blank=True, null=True, verbose_name=u'Motivo referenciado', on_delete=models.CASCADE)
    nombre = models.CharField(default='', max_length=200, verbose_name='Nombre del motivo de la sanción')
    descripcion = models.TextField(default='', verbose_name='Descripción')
    principal = models.BooleanField(default=False, verbose_name='¿Es principal?')

    def __str__(self):
        return self.nombre

    def requisitos(self):
        return self.requisitomotivosancion_set.filter(activo=True)

    def sub_motivos(self):
        return MotivoSancion.objects.filter(motivoref=self, status=True, principal=False).order_by('id')

    def existe_incidencia(self):
        return self.incidenciasancion_set.filter(status=True).exists()

    def existe_requisitomotivosancion(self):
        return self.requisitomotivosancion_set.filter(status=True).values('id').exists()

    class Meta:
        verbose_name = 'Motivo de Sanción'
        verbose_name_plural = 'Motivos de Sanción'
        ordering = ['-id']

class RequisitoMotivoSancion(ModeloBase):
    requisito = models.ForeignKey(RequisitoSancion, on_delete=models.CASCADE, verbose_name='Requisito de sanción')
    motivo = models.ForeignKey(MotivoSancion, on_delete=models.CASCADE, verbose_name='Motivo de sanción')
    activo = models.BooleanField(default=True, verbose_name='Activo')
    obligatorio = models.BooleanField(default=True, verbose_name='¿Es obligatorio?')
    punto_control = models.IntegerField(default=0, choices=PUNTO_CONTROL, verbose_name='Punto de Control')

    def __str__(self):
        return self.requisito.nombre

    def existe_incidencia(self):
        return self.evidenciapersonasancion_set.filter(persona_sancion__incidencia__status=True ).values('id').exists()

    class Meta:
        verbose_name = 'Requisito de motivo de sanción'
        verbose_name_plural = 'Requisitos de motivos de sanciones'
        ordering = ['-id']

class PuntoControl(ModeloBase):
    nombre = models.CharField(default='', max_length=200, verbose_name='Nombre de la entrada')
    slug = models.SlugField(default='', max_length=200, verbose_name='Slug')
    # object_id = models.IntegerField(blank=True, null=True, verbose_name="Id de objeto")
    content_type = models.ForeignKey(ContentType, models.SET_NULL, verbose_name=u'Modelo', blank=True, null=True)
    motivos = models.ManyToManyField(MotivoSancion, verbose_name='Motivos de sanción')

    def __str__(self):
        return f'{self.nombre}'

    class Meta:
        verbose_name = 'Punto de Control'
        verbose_name_plural = 'Puntos de control'
        ordering = ['-id']

class IncidenciaSancion(ModeloBase):
    falta = models.ForeignKey(FaltaDisciplinaria, blank=True, null=True, on_delete=models.CASCADE, verbose_name='Falta disciplinaria')
    codigo = models.CharField(default='', max_length=100, verbose_name='Código del proceso')
    numero = models.IntegerField(default=0, verbose_name='Numero de incidencia')
    persona = models.ForeignKey('sga.Persona', blank=True, null=True, on_delete=models.CASCADE, verbose_name='Responsable que crea la incidencia')
    departamento = models.ForeignKey('sagest.Departamento', on_delete=models.CASCADE, verbose_name='Departamento', blank=True, null=True)
    motivo = models.ForeignKey(MotivoSancion, blank=True, null=True, on_delete=models.CASCADE, verbose_name='Motivo de la sanción')
    etapa = models.IntegerField(default=1, choices=ETAPA_INCIDENCIA, verbose_name='Etapa de incidencia')
    estado = models.IntegerField(default=1, choices=ESTADO_INCIDENCIA, verbose_name='Estado de incidencia')
    observacion = models.TextField(default='', blank=True, null=True, verbose_name='Observación Reportada')
    fecha = models.DateTimeField(blank=True, null=True, verbose_name='Fecha de la falta cometida')
    fecha_fin = models.DateTimeField(blank=True, null=True, verbose_name='Fecha cuando se finalizo el caso')
    archivo = models.FileField(blank=True, null=True, upload_to='evidencia_sancion_noprocede/', verbose_name=u'Archivo incidencia caso')

    def __str__(self):
        return self.codigo

    def color_estado(self):
        if self.estado == 0:
            return 'text-muted'
        elif self.estado == 1:
            return 'text-primary'
        elif self.estado == 2:
            return 'text-success'
        elif self.estado == 3:
            return 'text-info'
        elif self.estado == 4:
            return 'text-secondary'
        elif self.estado >= 5:
            return 'text-primary'
        return 'text-danger'
    def personas_sancion(self):
        return self.personasancion_set.filter(status=True)

    def validador_th(self):
        return self.responsableetapaincidencia_set.filter(status=True,
                                                          etapa=2,
                                                          accion=1,
                                                          tipo_doc=1).last()
    def responsable_etapa(self, etapa, tipo_doc, accion):
        return self.responsableetapaincidencia_set.filter(status=True,
                                                          etapa=etapa,
                                                          accion=accion,
                                                          tipo_doc=tipo_doc).last()
    def puede_remitir_caso(self, persona):
        if estado == 1 and self.persona == persona:
            return True
        return estado

    def motivos(self):
        return self.falta.motivosancion_set.filter(status=True)
    def motivos_principales(self):
        return self.motivos().filter(status=True, principal=True)

    def documento(self, tipo_doc):
        return self.documentoetapaincidencia_set.filter(status=True,tipo_doc=int(tipo_doc)).last()

    def personas_sancion_text(self):
        personas = self.personas_sancion_prodecedente().filter(estado=1)
        palabra = 'el servidor'
        if len(personas) > 1:
            palabra = f'los servidores'
        for idx, per in enumerate(personas):

api/forms/my_form.py
# -*- coding: utf-8 -*-
import os

from django import forms
from django.forms import ModelForm
from django.forms.utils import ErrorList
from django.utils.safestring import mark_safe


class CheckboxSelectMultipleCustom(forms.CheckboxSelectMultiple):
    def render(self, *args, **kwargs):
        output = super(CheckboxSelectMultipleCustom, self).render(*args, **kwargs)
        return mark_safe(output.replace(u'<ul>', u'<div class="custom-multiselect" style="width: 600px;overflow: scroll"><ul>').replace(u'</ul>', u'</ul></div>').replace(u'<li>', u'').replace(u'</li>', u'').replace(u'<label', u'<div style="width: 900px"><li').replace(u'</label>', u'</li></div>'))


class ExtFileField(forms.FileField):
    """
    * max_upload_size - a number indicating the maximum file size allowed for upload.
            500Kb - 524288
            1MB - 1048576
            2.5MB - 2621440
            5MB - 5242880
            10MB - 10485760
            20MB - 20971520
            50MB - 5242880
            100MB 104857600
            250MB - 214958080
            500MB - 429916160
    t = ExtFileField(ext_whitelist=(".pdf", ".txt"), max_upload_size=)
    """

    def __init__(self, *args, **kwargs):
        ext_whitelist = kwargs.pop("ext_whitelist")
        self.ext_whitelist = [i.lower() for i in ext_whitelist]
        self.max_upload_size = kwargs.pop("max_upload_size")
        super(ExtFileField, self).__init__(*args, **kwargs)

    def clean(self, *args, **kwargs):
        upload = super(ExtFileField, self).clean(*args, **kwargs)
        if upload:
            size = upload.size
            filename = upload.name
            ext = os.path.splitext(filename)[1]
            ext = ext.lower()
            if size == 0 or ext not in self.ext_whitelist or size > self.max_upload_size:
                raise forms.ValidationError("Tipo de fichero o tamanno no permitido!")


class FixedForm(ModelForm):
    date_fields = []

    def __init__(self, *args, **kwargs):
        super(ModelForm, self).__init__(*args, **kwargs)
        for f in self.date_fields:
            self.fields[f].widget.format = '%d-%m-%Y'
            self.fields[f].input_formats = ['%d-%m-%Y']


class MY_Form(forms.Form):
    _errors_aux = {}

    def __init__(self, data=None, files=None, auto_id='id_%s', prefix=None,
                 initial=None, error_class=ErrorList, label_suffix=None,
                 empty_permitted=False, field_order=None, use_required_attribute=None, renderer=None):
        super(MY_Form, self).__init__(data=data, files=files, auto_id=auto_id, prefix=prefix, initial=initial,
                                      error_class=error_class, label_suffix=label_suffix,
                                      empty_permitted=empty_permitted, field_order=field_order,
                                      use_required_attribute=use_required_attribute, renderer=renderer)

    def addError(self, field, message):
        self._errors_aux[field] = message

    def addErrors(self, errors):
        self._errors_aux = errors

    def getError(self, field):
        return self._errors_aux[field]

    def getErrors(self):
        return self._errors_aux

    def clearErrors(self):
        self._errors_aux = {}

    def isErrorEmpty(self):
        return True if self._errors_aux else False

    def toArray(self):
        fields = []
        for field in self.fields:
            # print(self.fields[field])
            # print(type(self.fields[field]))
            if isinstance(self.fields[field], forms.BooleanField):
                value = False
                if field in self.data:
                    if self.data[field].lower() in ('false', '0'):
                        value = False
                    else:
                        value = bool(self.data[field])
                fields.append({'field': field, 'value': value})
            else:
                fields.append({'field': field, 'value': self.data[field] if field in self.data and self.data[field] else ''})

        return {'errors': self._errors_aux, "fields": fields}

    def toArrayLogin(self):
        fields = {'username': self.data['username'] if 'username' in self.data and self.data['username'] else '',
                  'password': '',
                  }
        # toArray.update(arr)
        return {'errors': self._errors_aux, "fields": fields}

    def disable_field(self, name_field):
        self.fields[name_field].widget.attrs['readonly'] = True
        self.fields[name_field].widget.attrs['disabled'] = True

    def enable_field(self, name_field):
        self.fields[name_field].widget.attrs['readonly'] = False
        self.fields[name_field].widget.attrs['disabled'] = False

    def reading_mode_field(self, name_field, value):
        self.fields[name_field].widget.attrs['readonly'] = value

    def lock_mode_field(self, name_field, value):
        self.fields[name_field].widget.attrs['disabled'] = value

    def view(self):
        for field in self.fields:
            self.disable_field(field)

directivo/templates/adm_directivos/forms/formplanificar.html
{% extends 'ajaxformmodal.html' %}
{% load sga_extras %}
{% block extra_js %}
    <script>
        numDetalle = {{ numDetalle }}+1;
        optionsHtml = '<option value=""></option>'
        $(function(){
            let bloque = $("#id_bloque")
            let ubicacion = $("#id_ubicacion")
            cargarSelectSecundario('cargarubicaciones', bloque, ubicacion)
            {% if numDetalle > 0 %}
                buscarPersona($(`.funcionarios`), 'distributivos')
            {% endif%}
            {% if audiencia.estado > 0 and not action == 'reprogramaraudiencia' %}
                $("#id_fecha, #id_horainicio, #id_horafin").attr('readonly', true)
                $("#fieldset_notificar").hide()
            {% endif %}
            {% for rol in roles %}
                optionsHtml += `<option value="{{ rol.0 }}">{{ rol.1 }}</option>`
            {% endfor %}
        })
        function crearFilaDetalle(numDetalle) {
            return $('<tr>', { 'id': `tr_${numDetalle}`, 'data_id': numDetalle }).append(
                $('<td>').append(
                    $('<select>', {
                        'class': 'form-control p-1 my-1 funcionarios select2',
                        'id': `id_funcionario${numDetalle}`,
                        'api':true,
                        'name': 'funcionario',
                        'required': true
                    })
                ),
                $('<td>').append(
                    $('<select>', {
                        'class': 'form-control p-1 my-1 select2 roles',
                        'name': 'rol',
                        'required': true
                    }).append(optionsHtml)),
                $('<td>', { 'class': 'text-center' }).append(
                    $('<a>', {
                        'href': 'javascript:void(0)',
                        'class': 'btn btn-danger btn-mini',
                        'onclick': `eliminarFilaDetalle(${numDetalle})`
                    }).append('<i class="fa fa-trash"></i>')
                )
            );
        }

        function agregarFilaDetalle() {
            $('#id_tabla_registro tbody').append(crearFilaDetalle(numDetalle));
            let funcionario = $(`#id_funcionario${numDetalle}`)
            buscarPersona(funcionario)
            $(".roles").select2({width: '100%',
                                placeholder: 'Seleccione una opción...',
                                minimumResultsForSearch: 15})
            numDetalle += 1;
        }

        function eliminarFilaDetalle(id) {
            $(`#tr_${id}`).remove();
            numDetalle -= 1;
        }

        function funcionAntesDeGuardar(){
            {#$("#id_fecha, #id_horainicio, #id_horafin").removeAttr('disabled')#}
              lista_items1 = []
                $('table#id_tabla_registro > tbody tr').each(function (index, elementTr) {
                    let id_persona = $(elementTr).find('td > select.funcionarios').val()
                    if (id_persona){
                        lista_items1.push({
                            'id_persona': id_persona,
                            'rol': $(elementTr).find('td > select.roles').val()
                        });
                    }
                });
        }
    </script>
{% endblock %}
{% block header_info %}
    {% if audiencia.estado > 0 and not action == 'reprogramaraudiencia' %}
        <div class="alert alert-warning d-flex align-items-center p-2" role="alert">
            <svg class="bi flex-shrink-0 me-2" width="20" height="20" role="img" aria-label="Info:">
                <use xlink:href="#info-fill"/>
              </svg>
            <div class="lh-15">
                <p class="ps-2 fs-5">
                   Esta audiencia ya fue notificada por lo tanto no podra moficiar los campos de fecha, hora de inicio y hora de fin.
                </p>
            </div>
        </div>
    {% endif %}
{% endblock %}
{% block extra_input %}
    <div class="alert alert-primary d-flex align-items-center p-2 justify-content-start my-2" role="alert">
        <svg class="bi flex-shrink-0 me-2" width="20" height="20" role="img" aria-label="Info:">
            <use xlink:href="#info-fill"/>
          </svg>
        <div class="lh-15">
            <p class="ps-2 fs-5">
                Recuerde que si el participante no se encuentra registrado en ninguno de nuestros sistemas, puede registrarlo en el siguiente enlace.
            </p>
        </div>
        <div class="text-center w-20">
            <a href="javascript:void(0)" class="btn btn-primary-old btn-sm"
                  onclick="formModalBase('','Adicionar persona externa','signup','','modal-md',true,'fa fa-user-plus')">
                  <i class="fa fa-user-plus"></i>
                  Registrar
            </a>
        </div>
    </div>
	<table class="table table_primary" id="id_tabla_registro">
        <thead>
            <tr>
                <th class="w-70">Participante de audiencia</th>
                <th class="w-30 text-center">Rol</th>
                <th class="w-3 text-center">
                    <a href="javascript:void(0)"
                     onclick="agregarFilaDetalle()"
                     class="btn btn-success btn-mini"><i class="bi bi-plus-lg"></i></a>
                </th>
            </tr>
        </thead>
        <tbody id="id_tbody">
            {% for p in incidencia.personas_sancion_prodecedente %}
                <tr >
                    <td>
                        <div class="d-flex align-items-center">
                            <img src="{{ p.persona.get_foto }}" alt="" class="rounded-circle avatar-sm me-1">
                            <p class="mb-0 lh-15">
                                {{ p.persona.nombre_completo_minus }}
                            </p>
                        </div>
                    </td>
                    <td class="text-center" >Servidor Público </td>
                    <td>
                    </td>
                </tr>
            {% endfor %}
            {% if audiencia %}
                 {% for p in responsables_audiencia %}
                    <tr id="tr_{{ forloop.counter }}" data_id="{{ forloop.counter }}">
                        <td>
                            <select name="funcionario" id="id_funcionario" api="true" class="select2 funcionarios">
                                <option value="{{ p.persona.id }}">{{ p.persona }}</option>
                            </select>
                        </td>
                        <td class="align-middle text-center">
                             <select name="rol" id="id_rol" class="select2 roles" disabled>
                                {% for rol in roles %}
                                    <option value="{{ rol.0 }}" {% if rol.0 == p.rol_firma %}selected{% endif %}>{{ rol.1 }}</option>
                                {% endfor %}
                            </select>
                        </td>
                        <td class="align-middle text-center">
                            <a href="javascript:void(0)"  class="btn btn-danger btn-mini"
                                onclick="eliminarFilaDetalle({{ forloop.counter }})"><i class="fa fa-trash"></i></a>
                        </td>
                    </tr>
                {% endfor %}
            {% else %}
                 {% for p in responsables_firma %}
                    <tr id="tr_{{ forloop.counter }}" data_id="{{ forloop.counter }}">
                        <td>
                            <select name="funcionario" id="id_funcionario" api="true" class="select2 funcionarios">
                                <option value="{{ p.persona.id }}">{{ p.persona }}</option>
                            </select>
                        </td>
                        <td class="align-middle text-center">
                             <select name="rol" id="id_rol" class="select2 roles" disabled>
                                {% for rol in roles %}
                                    <option value="{{ rol.0 }}" {% if rol.0 == p.rol_doc %}selected{% endif %}>{{ rol.1 }}</option>
                                {% endfor %}
                            </select>
                        </td>
                        <td class="align-middle text-center">
{#                            <a href="javascript:void(0)"  class="btn btn-danger btn-mini"#}
{#                                onclick="eliminarFilaDetalle({{ forloop.counter }})"><i class="fa fa-trash"></i></a>#}
                        </td>
                    </tr>
                {% endfor %}
            {% endif %}
        </tbody>
    </table>
{% endblock %}

directivo/templates/adm_directivos/forms/formrevision.html
{% extends 'base.html' %}
{% load sga_extras %}
{% block atras %}{{ url_atras }}{% endblock %}
{% block heading %}
    <script src="/static/adicionalesjs/formquestionb4.js?0.24"></script>
    <script>
        $(function () {
            MenuFijo();
            $("#contentForm .select2").select2({
                width: '100%',
                placeholder: 'Seleccione una opción.',
                minimumResultsForSearch: 15
            })
            {% if mostrar_notificacion %}
                let tiempoRestante = {{ tiempo_restante }};

                function formatTime(seconds) {
                    let hours = Math.floor(seconds / 3600);
                    let minutes = Math.floor((seconds % 3600) / 60);
                    let secs = seconds % 60;

                    // Asegurarse de que siempre se muestren dos dígitos
                    hours = hours < 10 ? `0${hours}` : hours;
                    minutes = minutes < 10 ? `0${minutes}` : minutes;
                    secs = secs < 10 ? `0${secs}` : secs;
                    secs = Math.floor(secs);
                    return `${hours}:${minutes}:${secs}`;
                }

                // Mostrar el tiempo inicial en la pantalla
                document.getElementById("cronometro").textContent = formatTime(tiempoRestante);

                // Función que actualiza el cronómetro cada segundo
                const countdown = setInterval(function () {
                // Disminuye el tiempo restante
                tiempoRestante--;

                // Muestra el tiempo actualizado en formato HH:MM:SS
                document.getElementById("cronometro").textContent = formatTime(tiempoRestante);

                // Si el tiempo llega a 0, detén el cronómetro
                if (tiempoRestante <= 0) {
                    clearInterval(countdown);
                    document.getElementById("cronometro").textContent = "00:00:00";
                }
            }, 1000); // El cronómetro se actualiza cada 1000 ms (1 segundo)
            {% endif %}


        });

    </script>
    <style>
        .cronometro {
            font-size: 1.5rem;
            font-weight: bold;
        }

    </style>
{% endblock %}
{% block canvas %}
    <div class="row">
        <div class="col-lg-4 col-sm-12">
            <div class="headtitle">
                <h3 class="texto-blue ">{{ title }}</h3>
                <h6><i class="bi bi-diagram-3 fs-4"></i> {{ incidencia.departamento|title2 }}</h6>
            </div>
        </div>
        <div class="col-lg-8 col-sm-12 px-4">
             {% if mostrar_notificacion %}
                {% if tiempo_restante > 0 %}
                    <div class="d-flex align-items-center gap-1 alert alert-info my-0 py-2 lh-15">
                        <div><img src="/static/images/undraw/caution.png" style="width: 40px;"></div>
                        <div>
                            <h4 class="lh-15 mb-1">Acciones pendientes de realizar</h4>
                            <p class="mb-0">
                                {{ text_tiempo_restante }}
                            </p>
                        </div>
                        <p id="cronometro" class="text-orange cronometro ms-auto">23:00:12</p>

                    </div>
                {% else %}
                    <div class="alert alert-danger my-0 py-2 lh-15">
                        <p class="mb-0">
                            {{ text_tiempo_fin }}
                        </p>
                    </div>
                {% endif %}
            {% endif %}
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-4">
                {% include 'adm_directivos/forms/infoseccion_incidencia.html' %}
            </div>
            <div class="col-lg-8">
                <div class="card">
                    <div class="card-body p-4 pt-2">
                        {% with ePermisos=incidencia|args:1|args:persona|call:'permisos_sancion' %}
                            {% include 'adm_directivos/forms/etapaseccion_incidencia.html' %}
                        {% endwith %}
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

directivo/templates/adm_directivos/forms/infoseccion_incidencia.html
{% load sga_extras %}
<div class="card py-2 px-1 caja-menu">
    <!-- Card body -->
    <div class="card-body">
        <div class="d-flex align-items-center">
            <div class="">
                <h4 class="mb-1 texto-blue"><i class="bi bi-upc-scan"></i> {{ incidencia.codigo }}</h4>
                <p class="mb-1 fs-6 text-secondary"><i
                        class="bi bi-calendar-week"></i> {{ incidencia.fecha_creacion|date:'d-m-Y' }}
                </p>
            </div>
        </div>
        <div class="py-3 border-top">
            <p class="fw-semi-bold"><i class="bi bi-chat-left-text"></i> Observación:</p>
            <p class="ms-3 lh-15">{{ incidencia.observacion }}</p>
            <div class="d-flex align-items-center pt-1 mx-3">
                <img src="{{ incidencia.persona.get_foto }}" alt="" class="rounded-circle avatar-xs me-1">
                <h6 class="mb-0 lh-15 text-truncate">
                    {{ incidencia.persona.nombre_completo_minus }}
                    <br>
                    <span class="fs-6 fw-normal">{{ incidencia.persona.mi_cargo_administrativo|default_if_none:''|title2 }}</span>

                </h6>
            </div>
        </div>
        <div class="py-3 border-top lh-15">
{#                            <p class="mb-2">#}
{#                                <i class="bi bi-ui-radios-grid"></i>#}
{#                                <b>Punto de control: </b><span class="fw-normal">{{ incidencia.punto_control }}</span>#}
{#                            </p>#}
            <p class="">
                <i class="bi bi-patch-exclamation"></i>
                <b>Clasificación:</b>
            </p>
            <p class="ms-3 mb-2">{{ incidencia.motivo.motivoref|default_if_none:''|title2 }}</p>
            <p class="">
                <b><i class="bi bi-patch-exclamation"></i> Sub clasificación:</b>
            </p>
            <p class="ms-3 mb-1 text-orange">{{ incidencia.motivo|default_if_none:''|title2 }}</p>
        </div>
        <div class="border-top row mt-1 border-bottom mb-3 g-0">
            {#                            <div class="col">#}
            {#                                <div class="pe-1 ps-2 py-3">#}
            {#                                    <h5 class="mb-0">11,604</h5>#}
            {#                                    <span>Students</span>#}
            {#                                </div>#}
            {#                            </div>#}
            <div class="col ">
                <div class="pe-1 ps-3 py-3">
                    <h5 class="mb-0 {{ incidencia.color_estado }} text-truncate" id="num_inte">
                        {{ incidencia.get_estado_display }}
                    </h5>
                    <span>Estado</span>
                </div>
            </div>
            <div class="col border-start">
                <div class="pe-1 ps-3 py-3">
                    <h5 class="mb-0 text-orange">{{ incidencia.falta|title }}</h5>
                    <span>Falta</span>
                </div>
            </div>
        </div>

    </div>
</div>